# Generated by Django 3.2.15 on 2023-05-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
