# Generated by Django 3.2.15 on 2023-05-24 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0002_parking_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='parking_user',
            new_name='parking_user_X',
        ),
    ]
