# Generated by Django 3.2.15 on 2023-05-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0002_alter_category_categoryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='lostDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='lostDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='lostDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
