# Generated by Django 3.2.15 on 2023-05-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0003_auto_20230505_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founditem',
            old_name='lostDateTime',
            new_name='foundDateTime',
        ),
    ]
