# Generated by Django 3.2.15 on 2023-05-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0003_rename_parking_user_parking_user_x'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newUser',
            field=models.BooleanField(default=True),
        ),
    ]
