# Generated by Django 3.2.15 on 2023-05-06 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0004_rename_lostdatetime_founditem_founddatetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grievance',
            old_name='lostDateTime',
            new_name='occuranceDateTime',
        ),
    ]
