# Generated by Django 3.2.15 on 2023-05-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0005_rename_lostdatetime_grievance_occurancedatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beatbox',
            name='beatBoxDescription',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='beatbox',
            name='beatBoxDescriptionO',
            field=models.CharField(max_length=1000),
        ),
    ]
