# Generated by Django 3.2.15 on 2023-05-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0007_auto_20230507_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilities',
            name='facilityLogoId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
