# Generated by Django 3.2.15 on 2023-05-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0008_facilities_facilitylogoid'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageStorage',
            fields=[
                ('imageId', models.AutoField(primary_key=True, serialize=False)),
                ('eventId', models.CharField(max_length=255)),
                ('functionName', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('modifyDate', models.DateTimeField()),
                ('delFlag', models.BooleanField(default=False)),
            ],
        ),
    ]
