# Generated by Django 3.2.15 on 2023-05-09 12:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0009_imagestorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestorage',
            name='image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to=''), size=None),
        ),
    ]
