# Generated by Django 3.2.15 on 2023-05-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0010_alter_imagestorage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imageStorage',
        ),
    ]
