# Generated by Django 3.2.15 on 2023-05-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0013_alter_imagestorage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestorage',
            name='image',
            field=models.BinaryField(),
        ),
    ]
