# Generated by Django 3.2.15 on 2023-05-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0014_alter_imagestorage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
