# Generated by Django 3.2.15 on 2023-05-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0015_grievance_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='updatedBy',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='updatedBy',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='updatedBy',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
