# Generated by Django 3.2.15 on 2023-05-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0016_auto_20230510_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestorage',
            name='image',
            field=models.TextField(),
        ),
    ]
