# Generated by Django 3.2.15 on 2023-05-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0017_alter_imagestorage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddistribution',
            name='preferedDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
